### ISSUE TITLE
Add AzureDevops

### ISSUE THREAD

**Issue by MarcBruins** [NuKeeperDotNet/NuKeeper#489]
We should a AzureDevops and others to the tool. To do this the code should be more friendly towards new clients. At the moment there is very tight coupling with Github. My initial pr #480 was to big to review and had to many major decisions. In this issue i would like to list the small steps that we need to take towards a better solution. By making small steps the process becomes more understandable and it's easier for people to drop in and help out.

- [x] Make projects .NET standard #482 
- [x] Add a new Abstraction project #490
- [x] Code Search DTO #491 
- [x] User DTO #491 
- [x] Organisation DTO #491 
- [x] GitRepository DTO #491 
- [x] Pull Request DTO #491 
- [x] Collaboration platform DTO #491 
- [x] Make IGithub use DTO's #491 
- [x] Setup NuKeeper.Github project #497 
- [x] Move helpers to abstractions #493 
- [x] Abstract logging #492 
- [x] Make configuration more generic #490 
- [x] Add AzureDevops commands 
- [x] Add new AzureDevops project #502 

Work that still needs to be done:

- [x] Add Collaboration Factory
- [x] Add tests to AzureDevOps Project
- [x] Make AzureDevOps API Calls more efficient
- [x] Implement additional ForkMode's for AzureDevOps
- [x] Implement additional RepositoryDiscovery Methods for AzureDevOps
- [x] Work out how Global and Org commands work in a multiplatform world
- [x] Review Command arguments (this may be a breaking change if we are not careful)

Bonus work
- [x] Reorganize test projects
- [x] Add more unit tests

**Comment by shep1987** [comment]
From the last few days some ideas on how to spit the work...

### Concepts to move into Abstractions project

**Configuration**
Will need to make some of the Props a bit more generic

**Git**
This shouldn't require much change

**Local**
This shouldn't require much change

**Engine**
Will need to swap from octokit DTO's to new Abstractions DTO's

**DTOs**
Code Search
User
Organisation
GitRepository
Pull Request
Collaboration platform

### Collaboration platform
Should follow a interface close to IGitHub
Should be implemented in own project
Github to continue using octokit
AzureDevops to use rest API and PAT, work out how to talk to Git (used alternative credentials in POC)

**Comment by AnthonySteele** [comment]
I had a quick look, and haven't decided on first step.

Create a `NuKeeper.GitHub.csproj` project? Nope, it would depend on things currently in `NuKeeper.csproj` such as settings, you need to move these out first.

Create a `NuKeeper.Abstractions.csproj` project? Possible.

Get `IGithub` to return smaller, NuKeeper's won DTOs? Possible. This may be the necessary first step.

**Comment by AnthonySteele** [comment]
I think that it's time for the code that uses the `Octokit` github client library to move into a separate project, e.g. `NuKeeper.Github.csproj`.  

I expect that `IGitHub` would not go with it, i.e. remain behind as a contract for various source-control providers. Or possibly the common contract has to be one step up the call stack?

I would prefer to keep the `Abstractions` project light, and not contain classes that are called "Engine", "Selection", or "do-er".  Possibly an "engine" project will emerge for those.

**Comment by shep1987** [comment]
I think the above task list is pretty much done or obsolete I believe these are the work items left to get this working 

- [ ] Add Collaboration Factory
- [ ] Add tests to AzureDevOps Project
- [ ] Make AzureDevOps API Calls more efficient
- [ ] Implement additional ForkMode's for AzureDevOps
- [ ] Implement additional RepositoryDiscovery Methods for AzureDevOps
- [ ] Work out how Global and Org commands work in a multiplatform world
- [ ] Review Command arguments (this may be a breaking change if we are not careful)

Bonus work
- [ ] Reorganize test projects
- [ ] Add more unit tests

**Comment by timmkrause** [comment]
Should this basically work now? A comment from #502 says "[...] but it does work".

Executed: `nukeeper repo https://dev.azure.com/something/else/_git/MyRepo t0k3nt0k3nt0k3nt0k3nt0k3nt0k3nt0k3nt0k3nt0k3nt0k3nt0`
Got back: `Could not read repository URI: 'https://dev.azure.com/something/else/_git/MyRepo'

**Comment by AnthonySteele** [comment]
it's not in `0.9.2`. 
Right now a lot of the work has been done, but it's not surfaced yet. Probably in the next release.

**Comment by timmkrause** [comment]
Sorry for being impatient. Just watching your work and curious to try it out.
Thank you Anthony & team, really appreciate it.

**Comment by AnthonySteele** [comment]
So the focus now is e.g. that when you run `nukeeper repo https://dev.azure.com/something/else/_git/MyRepo `, nukeeeper has to inspect that url and decide which system to use - github or azure. Or we need to tell it which, with some commandline option if it can't be inferred. 

And the default api base for `https://api.github.com/` should not be applied if it's azure, which had a different standard api url.

**Comment by MarcBruins** [comment]
This is working in 0.10.0(will be released soon). Great job everyone 🍻
